### ISSUE TITLE
failure to extract base from fasta file - vt error

### ISSUE THREAD

**Issue by indapa** [atks/vt#28]
```$HOME/vt/vt normalize my.sorted.vcf  -r $HOME/Genomes/hg19/hg19.fa
    
    [variant_manip.cpp:464 right_trim_or_left_extend] failure to extract base from fasta file: 1:2338229
````
    
```[variant_manip.cpp:464 right_trim_or_left_extend] failure to extract base from fasta file: 1:2338229```

I have the following variant in this window:

```1   2338231 c.764_765insA   T   TT  .   .   OMIM=602859.0005;dbSNP=rs61750435;GENELIST=PEX10;CLINSIG=Pathogenic;TRAIT="Peroxisomebiogenesisdisorder6A";VT=Duplication;TRANSCRIPT=NM_002617.3;ASSEMBLY=GRCh37;METHOD=Eutils```

I’m a bit puzzled about the error. Is the fasta sequence not matching the allele listed in the VCF record?

**Comment by atks** [comment]
Hi Indapa,

The problem is probably with your reference file.  The names of the chromosomes have to be consistent with the chromosomes found in your VCF file.  I notice that you are using hg19.fa where  chromosome 1 is probably named as chr1 rather than 1.  It will be a good idea to download the GRCh37 fasta file in this case.

**Comment by indapa** [comment]
Got it. I downloaded the human_g1k_v37.fasta and it worked.
