### ISSUE TITLE
Normalization issue for indel

### ISSUE THREAD

**Issue by savishri** [atks/vt#37]
Hi,
I have below indel detected by Freebayes:

chr10   88679046        .       GAGCCCTG        GTGTAG

After running the normalization using vt, it became:
chr10	88679047	.	AGCCCT	TGTA

This is incorrect representation based on VCF spec. It should be:

chr10   88679046        .       GAGCCCT        GTGTA

Please let me know if it is possible to normalize in correct way.

Thanks
Savi

**Comment by savishri** [comment]
@atks 
@hyunminkang 
Please respond me about it. It will be very helpful.
Thanks

**Comment by atks** [comment]
Hi Savi,

The normalized representation by vt respects VCF4.2 specification.

"For simple insertions and deletions in which either the REF or one of the ALT alleles would otherwise be null/empty, the REF and ALT Strings must include the base before the event (which must be reflected in the POS field), unless the event occurs at position 1 on the contig in which case it must include the base after the event; this padding base is not required (although it is permitted) for e.g. complex substitutions or other events where all alleles have at least one base represented in their Strings. "

There is no need for a padding base for complex substitutions where all alleles have at least one base represented in their Strings.

**Comment by savishri** [comment]
@atks Thanks for the response. Does vt normalization for complex indel will always not have padded base before the event?
Another question I have is that if I run decompose using vt on a vcf where there are SNVs, insertions, deletions and complex indels are there, what will be the impact of this on insertions, deletions and complex indel.

Thanks

**Comment by atks** [comment]
vt normalize will remove any extraneous bases as long as it does not result in empty alleles.

vt decompose basically breaks down multiallelic variants into biallelic variants.  vt normalize should take place after this decomposition.

vt decompose_blocksub will break down biallelic block substitutions into SNPs.

A way to reduce all these variants for comparisons is to decompose, decompose_blocksub and then normalize.

For biallelic complex indels where there are indels, nothing is done to such cases as the decomposition is generally not unique.

The impact on the variants can be summarized by running vt peek on the resultant VCFs.  For vt's classification of variants, you can look at http://genome.sph.umich.edu/wiki/Variant_classification

**Comment by savishri** [comment]
Thanks a lot for this explaination.

**Comment by atks** [comment]
welcome. :)  Do let me know if there are any other queries.
