### ISSUE TITLE
trouble with bcf_ip2g

### ISSUE THREAD

**Issue by GuilhemSempere** [atks/vt#66]
Hi

Since I needed the exact same functionality as that of bcf_ip2g in my Java app, I thought I would translate your implementation to Java. However when I then started testing it I found myself in an infinite loop in some cases like bcf_ip2g(3,3) bcf_ip2g(3,4) or bcf_ip2g(4,4).

I first thought something was wrong in my code translation but after further investigation, I managed to get your program to launch this method with the above parameters, and never got a reply. So unless I am completely mistaken (which could be the case!) there might be a little bug somewhere. Would you mind having a quick look?

Thanks very much,

G.

**Comment by atks** [comment]
Thanks for reporting this bug, the problem was with the if statement for detecting an "overflow"

The fix is simply 
if (i>=leftover_genotype_index) to
if (i>=leftover_genotype_index || allele_index==max_allele_index)
in the for loop iterating over the alleles for a ploidy position.

The formulae and derivations for these type of computations can be found at
http://genome.sph.umich.edu/wiki/Relationship_between_Ploidy,_Alleles_and_Genotypes

**Comment by GuilhemSempere** [comment]
Thanks a lot for the fix. May I suggest to also fix bcf_ap2g by replacing
if (no_ploidy==1)
with something like
if (no_ploidy==1 || no_allele<=1)
?

This would return the correct value (0) for bcf_ap2g(0, n) and improve performance for bcf_ap2g(1, n)

**Comment by atks** [comment]
done, thanks.
