### ISSUE TITLE
Way to list all available tools in vt from command line?

### ISSUE THREAD

**Issue by tseemann** [atks/vt#92]
I naively thought the output of `vt` was the only tools available.
Then i saw `decompose_blocksubs` in a script and didn't understand where it came from.

I now realise there is ~65 tools availabe.
```
grep cmd== main.cpp  | wc -l
65
```
Could you add a `vt help` or `vt listtools` which lists/describes all 65 briefly?

**Comment by atks** [comment]
@tseemann 
not all the commands are meant for general use, the commands listed on the wiki https://genome.sph.umich.edu/wiki/Vt are supported for public use.

**Comment by atks** [comment]
I'll update that command line more appropriately at a later date.  Can you work with the most recent release for the time being?

**Comment by tseemann** [comment]
Not all the commands in the wiki are listed in the command line help?

**Comment by ttbek** [comment]
Yes, I just requested a wiki account to update what parts I manage to understand.  Unfortunately info is sparse outside of the wiki itself.  In particular the one that I encountered is that vt remove_overlap is now vt filter_overlap... and from this repo it looks like that change might be what, 3 years old?  Usage output is also different if it fails vs. if you give no arguments, that is, 'vt filter_overlap -h' (fails of course) and 'vt filter_overlap'  My point being not that the output is different, failing of course has an error, but that the usage part of the output is different.

**Comment by ttbek** [comment]
Also, even if something isn't for general public use, it should probably be documented.  It could include a warning, a message that use is not supported, etc... Maybe it's just me, but I loathe having things hidden from me.  

E.g. The gcc command going ahead and calling Clang on OSX was a real headache for me, because the version of Clang at the time had poor MPI support and I needed it compiling on there for CRAN...  I don't own or develop on a Mac, so I didn't expect this nonsense.  Abstractions are nice... until they leak.  So unless your abstraction is really 100% airtight it should be documented.  I get not having time to document something, I don't get saying it shouldn't be documented.  

Also, what happened with vt discover2?  I see it in some of the older TopMed pipelines, did that simply replace the old discover or am I using old discover over here and I should build from source to get disover2?
